# Generated by Django 5.0 on 2024-01-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('pnf', models.CharField(max_length=100, verbose_name='PNF')),
                ('seccion', models.CharField(max_length=100, verbose_name='Seccion')),
                ('semestre', models.IntegerField(verbose_name='Semestre')),
                ('cedula', models.IntegerField(verbose_name='Cedula')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envio')),
            ],
        ),
    ]
